# Generated by Django 2.0.7 on 2018-08-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ariadne_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='text',
            field=models.CharField(max_length=60),
        ),
    ]
